use std::fs;
use std::path::Path;

use typeshare_core::context::{ParseContext, ParseFileContext};
use typeshare_core::language::{CrateTypes, Language, Swift};

const GENERATED_NOTICE: &str = "// Generated from kibod/src/model.rs by `just generate-types`.\n// Do not edit this file by hand.\n\n";

fn main() {
    if let Err(error) = run() {
        eprintln!("type generation failed: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("type generator must live at tools/typegen");
    let source = root.join("kibod/src/model.rs");
    let destination = root.join("ios/Shared/GeneratedAPI.swift");
    let input = fs::read_to_string(&source)?;
    let parsed = typeshare_core::parser::parse(
        &ParseContext::default(),
        ParseFileContext {
            source_code: input,
            crate_name: "kibod".into(),
            file_name: "model.rs".into(),
            file_path: source,
        },
    )?
    .ok_or("model.rs contains no #[typeshare] types")?;
    if !parsed.errors.is_empty() {
        return Err(parsed.errors[0].error.clone().into());
    }
    let mut output = GENERATED_NOTICE.as_bytes().to_vec();
    Swift::default().generate_types(&mut output, &CrateTypes::default(), parsed)?;

    if std::env::args().any(|argument| argument == "--check") {
        return check(&destination, &output);
    }
    if fs::read(&destination).ok().as_deref() != Some(output.as_slice()) {
        fs::write(&destination, output)?;
    }
    Ok(())
}

fn check(destination: &Path, expected: &[u8]) -> Result<(), Box<dyn std::error::Error>> {
    if fs::read(destination).ok().as_deref() == Some(expected) {
        return Ok(());
    }
    Err(format!(
        "{} is stale; run `just generate-types`",
        destination.display()
    )
    .into())
}
