// Generated from kibod/src/model.rs by `just generate-types`.
// Do not edit this file by hand.

/*
 Generated by typeshare 1.13.4
 */

import Foundation

public struct KiboProject: Codable, Hashable, Identifiable, Sendable {
	public let id: String
	public let name: String
	public let created_at: UInt64

	public init(id: String, name: String, created_at: UInt64) {
		self.id = id
		self.name = name
		self.created_at = created_at
	}
}

public enum ConversationNameSource: String, Codable, Hashable, Sendable {
	case placeholder
	case transcript
	case manual
	case ai
}

public struct KiboConversation: Codable, Hashable, Identifiable, Sendable {
	public let id: String
	public let project_id: String
	public let name: String
	public let name_source: ConversationNameSource?
	public let created_at: UInt64
	/// Most recent durable event in this conversation. Older metadata does not
	/// contain this field, so readers fall back to `created_at` when it is zero.
	public let last_activity_at: UInt64?

	public init(id: String, project_id: String, name: String, name_source: ConversationNameSource?, created_at: UInt64, last_activity_at: UInt64?) {
		self.id = id
		self.project_id = project_id
		self.name = name
		self.name_source = name_source
		self.created_at = created_at
		self.last_activity_at = last_activity_at
	}
}

public struct CreateNamed: Codable, Hashable, Sendable {
	public let name: String

	public init(name: String) {
		self.name = name
	}
}

public struct CreateConversation: Codable, Hashable, Sendable {
	public let name: String?

	public init(name: String?) {
		self.name = name
	}
}

public struct CreateTurn: Codable, Hashable, Sendable {
	public let turn_id: String

	public init(turn_id: String) {
		self.turn_id = turn_id
	}
}

public struct EventsQuery: Codable, Hashable, Sendable {
	public let after: UInt64?

	public init(after: UInt64?) {
		self.after = after
	}
}

public struct SpeechQuery: Codable, Hashable, Sendable {
	public let from_sample: UInt64?

	public init(from_sample: UInt64?) {
		self.from_sample = from_sample
	}
}

/// A durable conversation event sent both as an HTTP JSON object and as one
/// JSON object per WebSocket text frame. The log accepts new event kinds over
/// time, so `kind` remains a string and kind-specific fields are optional.
public struct KiboEvent: Codable, Hashable, Sendable {
	public let seq: UInt64
	public let kind: String
	public let id: String?
	public let at: UInt64?
	public let clip: String?
	public let turn: String?
	public let text: String?
	public let error: String?
	public let audio: String?
	public let clips: [String]?
	public let answers: [String]?
	public let ms: UInt64?
	public let peak: UInt32?
	public let file: String?
	public let mime: String?
	public let recorded_at: UInt64?
	public let sha256: String?
	public let interaction_id: String?
	public let samples: UInt64?
	public let rate: UInt32?
	public let recovered: Bool?
	public let name: String?
	public let source: String?

	public init(seq: UInt64, kind: String, id: String?, at: UInt64?, clip: String?, turn: String?, text: String?, error: String?, audio: String?, clips: [String]?, answers: [String]?, ms: UInt64?, peak: UInt32?, file: String?, mime: String?, recorded_at: UInt64?, sha256: String?, interaction_id: String?, samples: UInt64?, rate: UInt32?, recovered: Bool?, name: String?, source: String?) {
		self.seq = seq
		self.kind = kind
		self.id = id
		self.at = at
		self.clip = clip
		self.turn = turn
		self.text = text
		self.error = error
		self.audio = audio
		self.clips = clips
		self.answers = answers
		self.ms = ms
		self.peak = peak
		self.file = file
		self.mime = mime
		self.recorded_at = recorded_at
		self.sha256 = sha256
		self.interaction_id = interaction_id
		self.samples = samples
		self.rate = rate
		self.recovered = recovered
		self.name = name
		self.source = source
	}
}

public struct ProjectsEnvelope: Codable, Hashable, Sendable {
	public let projects: [KiboProject]

	public init(projects: [KiboProject]) {
		self.projects = projects
	}
}

public struct ConversationsEnvelope: Codable, Hashable, Sendable {
	public let conversations: [KiboConversation]

	public init(conversations: [KiboConversation]) {
		self.conversations = conversations
	}
}

public struct EventsEnvelope: Codable, Hashable, Sendable {
	public let events: [KiboEvent]
	public let latest_seq: UInt64

	public init(events: [KiboEvent], latest_seq: UInt64) {
		self.events = events
		self.latest_seq = latest_seq
	}
}

public struct PutClipResponse: Codable, Hashable, Sendable {
	public let clip_id: String
	public let created: Bool

	public init(clip_id: String, created: Bool) {
		self.clip_id = clip_id
		self.created = created
	}
}

public struct PutRecordingPartResponse: Codable, Hashable, Sendable {
	public let recording_id: String
	public let sequence: UInt32
	public let created: Bool

	public init(recording_id: String, sequence: UInt32, created: Bool) {
		self.recording_id = recording_id
		self.sequence = sequence
		self.created = created
	}
}

public struct CompleteRecording: Codable, Hashable, Sendable {
	public let part_count: UInt32
	public let total_samples: UInt64

	public init(part_count: UInt32, total_samples: UInt64) {
		self.part_count = part_count
		self.total_samples = total_samples
	}
}

public struct CompleteRecordingResponse: Codable, Hashable, Sendable {
	public let clip_id: String
	public let created: Bool

	public init(clip_id: String, created: Bool) {
		self.clip_id = clip_id
		self.created = created
	}
}

public struct TurnResponse: Codable, Hashable, Sendable {
	public let turn_id: String
	public let clips: [String]
	public let created: Bool

	public init(turn_id: String, clips: [String], created: Bool) {
		self.turn_id = turn_id
		self.clips = clips
		self.created = created
	}
}
